var METADATA = {
  "SUN": {
    "instance_of": "star",
    "surface_temp_c": 15709726.8,
    "diameter_km": 1391400.0,
    "name_origin_url": "https://en.wikipedia.org/wiki/Sol_(mythology)",
  },
  "MERCURY": {
    "instance_of": "planet",
    "diameter_km": 4878.0,
    "distance_from_sun_au": 0.387,
    "orbital_period_days": 87.969,
    "surface_temp_c": -173.1,
    "name_origin_url": "https://en.wikipedia.org/wiki/Mercury_(mythology)",
  },
  "VENUS": {
    "instance_of": "planet",
    "diameter_km": 12103.6,
    "distance_from_sun_au": 0.723,
    "orbital_period_days": 224.7,
    "rotation_period_days": -243.021,
    "surface_temp_c": 464.0,
    "name_origin_url": "https://en.wikipedia.org/wiki/Venus_(mythology)",
  },
  "EARTH": {
    "instance_of": "planet",
    "diameter_km": 12742.0,
    "distance_from_sun_au": 1.0,
    "orbital_period_days": 365.256,
    "rotation_period_days": 1.0,
    "surface_temp_c": 15.0,
  },
  "MARS": {
    "instance_of": "planet",
    "distance_from_sun_au": 1.524,
    "orbital_period_days": 686.98,
    "rotation_period_days": 1.026,
    "surface_temp_c": -63.0,
    "diameter_km": 6779.0,
    "name_origin_url": "https://en.wikipedia.org/wiki/Mars_(mythology)",
  },
  "CERES": {
    "instance_of": "dwarf planet",
    "diameter_km": 939.4,
    "distance_from_sun_au": 2.766,
    "orbital_period_days": 1679.911,
    "rotation_period_days": 0.378,
    "name_origin_url": "https://en.wikipedia.org/wiki/Ceres_(mythology)",
  },
  "JUPITER": {
    "instance_of": "planet",
    "diameter_km": 142984.0,
    "distance_from_sun_au": 5.203,
    "orbital_period_days": 4332.589,
    "rotation_period_days": 0.413,
    "name_origin_url": "https://en.wikipedia.org/wiki/Jupiter_(mythology)",
  },
  "SATURN": {
    "instance_of": "planet",
    "diameter_km": 120536.0,
    "distance_from_sun_au": 9.555,
    "orbital_period_days": 10757.737,
    "rotation_period_days": 0.446,
    "surface_temp_c": -139.1,
    "name_origin_url": "https://en.wikipedia.org/wiki/Saturn_(mythology)",
  },
  "URANUS": {
    "instance_of": "planet",
    "diameter_km": 51118.0,
    "distance_from_sun_au": 19.189,
    "orbital_period_days": 30688.5,
    "rotation_period_days": 0.708,
    "surface_temp_c": -224.1,
    "name_origin_url": "https://en.wikipedia.org/wiki/Uranus_(mythology)",
  },
  "NEPTUNE": {
    "instance_of": "planet",
    "diameter_km": 49528.0,
    "distance_from_sun_au": 30.104,
    "orbital_period_days": 60193.2,
    "rotation_period_days": 0.667,
    "surface_temp_c": -201.1,
    "name_origin_url": "https://en.wikipedia.org/wiki/Neptune_(mythology)",
  },
  "PLUTO": {
    "instance_of": "dwarf planet",
    "diameter_km": 2376.0,
    "distance_from_sun_au": 39.482,
    "perihelion_au": 29.658,
    "aphelion_au": 49.305,
    "orbital_period_days": 90553.02,
    "rotation_period_days": 6.387,
    "surface_temp_c": -240.1,
    "name_origin_url": "https://en.wikipedia.org/wiki/Pluto_(mythology)",
  },
  "HAUMEA": {
    "instance_of": "dwarf planet",
    "diameter_km": 1595.0,
    "distance_from_sun_au": 42.961,
    "orbital_period_days": 102851.2,
    "rotation_period_days": 0.163,
    "surface_temp_c": -223.1,
    "name_origin_url": "https://en.wikipedia.org/wiki/Haumea_(mythology)",
  },
  "MAKEMAKE": {
    "instance_of": "dwarf planet",
    "diameter_km": 1478.0,
    "distance_from_sun_au": 45.56,
    "orbital_period_days": 112329.0,
    "rotation_period_days": 0.937,
    "name_origin_url": "https://en.wikipedia.org/wiki/Makemake_(deity)",
  },
  "ERIS": {
    "instance_of": "dwarf planet",
    "diameter_km": 2326.0,
    "distance_from_sun_au": 67.74,
    "perihelion_au": 38.271,
    "aphelion_au": 97.651,
    "orbital_period_days": 203645.1,
    "rotation_period_days": 1.079,
    "surface_temp_c": -243.1,
    "name_origin_url": "https://en.wikipedia.org/wiki/Eris_(mythology)",
  },
  "MOON": {
    "instance_of": "moon",
    "parent_body": "Earth",
    "diameter_km": 3476.2,
    "orbit_radius_km": 384400,
    "orbital_period_days": 27.322,
    "surface_temp_c": -178.1,
    "name_origin_url": "https://en.wikipedia.org/wiki/Luna_(goddess)",
  },
  "PHOBOS": {
    "instance_of": "moon",
    "parent_body": "Mars",
    "diameter_km": 22.5,
    "orbit_radius_km": 9377,
    "orbital_period_days": 0.319,
    "name_origin_url": "https://en.wikipedia.org/wiki/Phobos_(mythology)",
  },
  "DEIMOS": {
    "instance_of": "moon",
    "parent_body": "Mars",
    "diameter_km": 12.4,
    "orbit_radius_km": 23458,
    "orbital_period_days": 1.262,
    "name_origin_url": "https://en.wikipedia.org/wiki/Deimos_(mythology)",
  },
  "IO": {
    "instance_of": "moon",
    "parent_body": "Jupiter",
    "diameter_km": 3660.0,
    "orbit_radius_km": 421800,
    "orbital_period_days": 1.769,
    "surface_temp_c": -183.1,
    "name_origin_url": "https://en.wikipedia.org/wiki/Io_(mythology)",
  },
  "EUROPA": {
    "instance_of": "moon",
    "parent_body": "Jupiter",
    "orbit_radius_km": 671100,
    "orbital_period_days": 3.551,
    "surface_temp_c": -223.1,
    "diameter_km": 3121.6,
    "name_origin_url": "https://en.wikipedia.org/wiki/Europa_(mythology)",
  },
  "GANYMEDE": {
    "instance_of": "moon",
    "parent_body": "Jupiter",
    "orbit_radius_km": 1070400,
    "orbital_period_days": 7.154,
    "surface_temp_c": -203.1,
    "diameter_km": 5268.2,
    "name_origin_url": "https://en.wikipedia.org/wiki/Ganymede_(mythology)",
  },
  "CALLISTO": {
    "instance_of": "moon",
    "parent_body": "Jupiter",
    "diameter_km": 4821.0,
    "orbit_radius_km": 1882700,
    "orbital_period_days": 16.689,
    "surface_temp_c": -193.1,
    "name_origin_url": "https://en.wikipedia.org/wiki/Callisto_(mythology)",
  },
  "MIMAS": {
    "instance_of": "moon",
    "parent_body": "Saturn",
    "diameter_km": 415.6,
    "orbit_radius_km": 185520,
    "orbital_period_days": 0.942,
    "name_origin_url": "https://en.wikipedia.org/wiki/Mimas_(mythology)",
  },
  "ENCELADUS": {
    "instance_of": "moon",
    "parent_body": "Saturn",
    "orbit_radius_km": 237948,
    "orbital_period_days": 1.37,
    "surface_temp_c": -240.2,
    "diameter_km": 504.2,
    "name_origin_url": "https://en.wikipedia.org/wiki/Enceladus_(mythology)",
  },
  "TITAN": {
    "instance_of": "moon",
    "parent_body": "Saturn",
    "orbit_radius_km": 1221870,
    "orbital_period_days": 15.945,
    "surface_temp_c": -179.4,
    "diameter_km": 5148.0,
    "name_origin_url": "https://en.wikipedia.org/wiki/Titan_(mythology)",
  },
  "MIRANDA": {
    "instance_of": "moon",
    "parent_body": "Uranus",
    "diameter_km": 468.0,
    "orbit_radius_km": 129872,
    "orbital_period_days": 1.413,
    "surface_temp_c": -213.1,
    "name_origin_url": "https://en.wikipedia.org/wiki/Miranda_(The_Tempest)",
  },
  "TITANIA": {
    "instance_of": "moon",
    "parent_body": "Uranus",
    "orbit_radius_km": 436300,
    "orbital_period_days": 8.706,
    "rotation_period_days": 8.7,
    "surface_temp_c": -213.1,
    "diameter_km": 1576.8,
    "name_origin_url": "https://en.wikipedia.org/wiki/Titania_(A_Midsummer_Night%27s_Dream)",
  },
  "OBERON": {
    "instance_of": "moon",
    "parent_body": "Uranus",
    "orbit_radius_km": 583520,
    "orbital_period_days": 13.463,
    "diameter_km": 1522.8,
    "name_origin_url": "https://en.wikipedia.org/wiki/Oberon",
  },
  "TRITON": {
    "instance_of": "moon",
    "parent_body": "Neptune",
    "diameter_km": 2700.0,
    "orbit_radius_km": 354759,
    "orbital_period_days": -5.877,
    "surface_temp_c": -235.1,
    "name_origin_url": "https://en.wikipedia.org/wiki/Triton_(mythology)",
  },
  "CHARON": {
    "instance_of": "moon",
    "parent_body": "Pluto",
    "diameter_km": 1212.0,
    "orbit_radius_km": 19591,
    "orbital_period_days": 6.387,
    "name_origin_url": "https://en.wikipedia.org/wiki/Charon_(mythology)",
  },
  "TETHYS": {
    "instance_of": "moon",
    "parent_body": "Saturn",
    "orbit_radius_km": 294619,
    "orbital_period_days": 1.888,
    "surface_temp_c": -187.1,
    "diameter_km": 1062.2,
    "name_origin_url": "https://en.wikipedia.org/wiki/Tethys_(mythology)",
  },
  "DIONE": {
    "instance_of": "moon",
    "parent_body": "Saturn",
    "orbit_radius_km": 377420,
    "orbital_period_days": 2.737,
    "surface_temp_c": -186.1,
    "diameter_km": 1123.4,
    "name_origin_url": "https://en.wikipedia.org/wiki/Dione_(mythology)",
  },
  "RHEA": {
    "instance_of": "moon",
    "parent_body": "Saturn",
    "diameter_km": 1527.0,
    "orbit_radius_km": 527070,
    "orbital_period_days": 4.518,
    "name_origin_url": "https://en.wikipedia.org/wiki/Rhea_(mythology)",
  },
  "IAPETUS": {
    "instance_of": "moon",
    "parent_body": "Saturn",
    "orbit_radius_km": 3560820,
    "orbital_period_days": 79.322,
    "diameter_km": 1469.0,
    "name_origin_url": "https://en.wikipedia.org/wiki/Iapetus",
  },
  "ARIEL": {
    "instance_of": "moon",
    "parent_body": "Uranus",
    "diameter_km": 1156.0,
    "orbit_radius_km": 191020,
    "orbital_period_days": 2.52,
    "surface_temp_c": -213.1,
    "name_origin_url": "https://en.wikipedia.org/wiki/The_Rape_of_the_Lock",
  },
  "UMBRIEL": {
    "instance_of": "moon",
    "parent_body": "Uranus",
    "diameter_km": 1169.4,
    "orbit_radius_km": 266300,
    "orbital_period_days": 4.144,
    "name_origin_url": "https://en.wikipedia.org/wiki/The_Rape_of_the_Lock",
  },
  "VESTA": {
    "instance_of": "asteroid",
    "diameter_km": 525.4,
    "distance_from_sun_au": 2.362,
    "orbital_period_days": 1325.537,
    "rotation_period_days": 0.223,
    "surface_temp_c": -188.1,
    "name_origin_url": "https://en.wikipedia.org/wiki/Vesta_(mythology)",
  },
  "ORCUS": {
    "instance_of": "probable dwarf planet",
    "diameter_km": 917.0,
    "distance_from_sun_au": 39.174,
    "orbital_period_days": 89555.6,
    "name_origin_url": "https://en.wikipedia.org/wiki/Orcus_(mythology)",
  },
  "QUAOAR": {
    "instance_of": "probable dwarf planet",
    "diameter_km": 1260.0,
    "distance_from_sun_au": 43.388,
    "orbital_period_days": 104389.7,
    "rotation_period_days": 0.368,
    "surface_temp_c": -229.1,
    "name_origin_url": "https://en.wikipedia.org/wiki/Chinigchinix",
  },
  "ARROKOTH": {
    "instance_of": "trans-Neptunian object",
    "diameter_km": 35.0,
    "distance_from_sun_au": 44.505,
    "orbital_period_days": 108446.5,
    "rotation_period_days": 0.663,
  },
  "GONGGONG": {
    "instance_of": "probable dwarf planet",
    "diameter_km": 1230.0,
    "distance_from_sun_au": 67.476,
    "perihelion_au": 33.642,
    "aphelion_au": 101.311,
    "orbital_period_days": 201184.23,
    "rotation_period_days": 0.933,
    "name_origin_url": "https://en.wikipedia.org/wiki/Gong_Gong",
  },
  "SEDNA": {
    "instance_of": "probable dwarf planet",
    "diameter_km": 995.0,
    "distance_from_sun_au": 484.521,
    "perihelion_au": 76.0,
    "aphelion_au": 937.0,
    "orbital_period_days": 4705404.65,
    "rotation_period_days": 0.428,
    "surface_temp_c": -261.1,
    "name_origin_url": "https://en.wikipedia.org/wiki/Sedna_(mythology)",
  },
  "FAROUT": {
    "instance_of": "trans-Neptunian object",
    "diameter_km": 500.0,
    "distance_from_sun_au": 81.969,
    "perihelion_au": 38.0,
    "aphelion_au": 125.0,
    "orbital_period_days": 271063.936,
  },
  "FARFAROUT": {
    "instance_of": "trans-Neptunian object",
    "diameter_km": 400.0,
    "distance_from_sun_au": 80.178,
    "perihelion_au": 27.6,
    "aphelion_au": 132.0,
    "orbital_period_days": 262230.407,
  },
};
