var NAME_ORIGINS = {
  "SUN":       { text: "Known since ancient times — Romans called it Sol, Greeks called it Helios." },
  "MERCURY":   { text: "Named after the Roman messenger god, who ran errands for the gods at lightning speed — fitting, since Mercury races around the Sun faster than any other planet." },
  "VENUS":     { text: "Named after the Roman goddess of love and beauty, because it shines more brilliantly in the sky than anything except the Sun and Moon." },
  "EARTH":     { text: "From the Old English word eorþe, meaning ground or soil. It's the only planet in the solar system not named after a god." },
  "MARS":      { text: "Named after the Roman god of war, because its rusty red color reminded ancient people of blood." },
  "CERES":     { text: "Named after the Roman goddess of grain and harvests. When it was discovered in 1801, people thought it was a new planet — it turned out to be the largest object in the asteroid belt." },
  "JUPITER":   { text: "Named after the king of the Roman gods — a fitting name for the biggest planet in the solar system." },
  "SATURN":    { text: "Named after the Roman god of farming and time, who was also Jupiter's father. The ancient Romans thought Saturn was the edge of the solar system." },
  "URANUS":    { text: "Named after the ancient Greek god of the sky. It's unusual in being named from Greek mythology rather than Roman — and in rolling on its side as it orbits the Sun." },
  "NEPTUNE":   { text: "Named after the Roman god of the sea, because of its deep, churning blue color." },
  "PLUTO":     { text: "Named after the Roman god of the underworld — cold, dark, and far away. An 11-year-old girl named Venetia Burney suggested the name the day after its discovery in 1930." },
  "HAUMEA":    { text: "Named after the Hawaiian goddess of fertility and childbirth, patron deity of the Big Island of Hawaiʻi." },
  "MAKEMAKE":  { text: "Named after the creator god of the Rapa Nui people of Easter Island, who is said to have made humanity from red clay." },
  "ERIS":      { text: "Named after the Greek goddess of discord and strife — fitting, since its discovery in 2005 sparked a fierce debate that led to Pluto being reclassified as a dwarf planet." },
  "MOON":      { text: "Simply called the Moon — from the Old English word mōna. In Latin it's Luna, in Greek it's Selene. Ancient people have watched and named it for as long as humans have existed." },
  "PHOBOS":    { text: "Named after Phobos, the Greek god of fear — one of the twin sons of Ares (Mars), the god of war. Its sibling moon is named Deimos." },
  "DEIMOS":    { text: "Named after Deimos, the Greek god of dread — the other son of Ares (Mars). Together, Phobos and Deimos (Fear and Dread) follow their father into battle." },
  "IO":        { text: "Named after a priestess of Hera in Greek myth. Zeus fell in love with her and turned her into a cow to hide her from his jealous wife — now she's one of the most volcanically active worlds in the solar system." },
  "EUROPA":    { text: "Named after a Phoenician princess in Greek myth. Zeus disguised himself as a white bull, and she climbed on his back — he carried her to the island of Crete. Scientists think Europa may have a liquid ocean beneath its ice that could support life." },
  "GANYMEDE":  { text: "Named after a Trojan prince said to be the most beautiful mortal in the world. Zeus sent an eagle to bring him to Mount Olympus to be cup-bearer of the gods. Ganymede is also the largest moon in the entire solar system." },
  "CALLISTO":  { text: "Named after a huntress in Greek myth who was a companion of Artemis. Zeus transformed her into a bear, and later placed her in the sky as the constellation Ursa Major." },
  "MIMAS":     { text: "Named after one of the Giants of Greek mythology, born from the goddess Gaia. It looks strikingly like the Death Star from Star Wars." },
  "ENCELADUS": { text: "Named after a giant in Greek myth who was buried under Mount Etna by Athena. Enceladus shoots enormous geysers of water ice into space — and may have a warm ocean under its surface." },
  "TITAN":     { text: "Named after the Titans, the powerful elder gods of Greek mythology who ruled the universe before Zeus and the Olympians. Titan is Saturn's largest moon and the only moon in the solar system with a thick atmosphere." },
  "MIRANDA":   { text: "Named after Miranda from Shakespeare's play The Tempest — a young woman who has lived her whole life on a magic island and is amazed by the outside world. Most of Uranus's moons are named after Shakespeare characters." },
  "TITANIA":   { text: "Named after the queen of the fairies in Shakespeare's A Midsummer Night's Dream." },
  "OBERON":    { text: "Named after the king of the fairies in Shakespeare's A Midsummer Night's Dream — Titania's husband." },
  "TRITON":    { text: "Named after the Greek god of the sea, son of Poseidon (Neptune). Triton swims backward — it orbits Neptune in the opposite direction from most moons, which may mean Neptune captured it long ago." },
  "CHARON":    { text: "Named after the ferryman of the dead in Greek mythology, who carried souls across the River Styx into the underworld. Charon is so large relative to Pluto that the two essentially orbit each other." },
  "TETHYS":    { text: "Named after a Titan goddess of fresh water in Greek mythology, daughter of the sky god Uranus and the earth goddess Gaia." },
  "DIONE":     { text: "Named after a Titan goddess in Greek mythology, sometimes described as a mother of Aphrodite (the goddess of love)." },
  "RHEA":      { text: "Named after the great mother goddess of Greek mythology — mother of Zeus, Hera, Poseidon, Demeter, and other Olympians." },
  "IAPETUS":   { text: "Named after the Titan god of mortality in Greek mythology, father of Prometheus. It has one face as white as snow and the other as black as coal." },
  "ARIEL":     { text: "Named after a mischievous spirit in Alexander Pope's comic poem The Rape of the Lock — a sylph who guards a beautiful woman. Most of Uranus's moons are named after characters from Shakespeare and Pope." },
  "UMBRIEL":   { text: "Named after a dark, melancholy sprite in Alexander Pope's The Rape of the Lock — the poem also inspired the naming of Ariel." },
  "VESTA":     { text: "Named after the Roman goddess of the hearth and home. Vesta is so bright it can occasionally be seen with the naked eye from Earth." },
  "ORCUS":     { text: "Named after a god of the underworld in Etruscan and Roman mythology — an older, more fearsome version of Pluto." },
  "QUAOAR":    { text: "Named after Qua-o-ar, the creator god of the Tongva people, who are indigenous to the Los Angeles area of California. The name was suggested by the discoverers to honor Native American traditions." },
  "ARROKOTH":  { text: "Named using the Powhatan/Algonquian word for sky. The New Horizons spacecraft flew past it in 2019 — it's the most distant object ever visited by a spacecraft, shaped like a snowman." },
  "GONGGONG":  { text: "Named after a Chinese water god with red hair and a serpent's tail, said to have caused a great flood by crashing into a mountain that held up the sky." },
  "SEDNA":     { text: "Named after the Inuit goddess of the sea, who is said to live at the bottom of the Arctic Ocean. Sedna takes about 11,400 years to complete one orbit around the Sun." },
  "FAROUT":    { text: "Nicknamed FarOut by its discoverers because it was the most distant object ever observed in the solar system when first spotted in 2018 — at 126 times farther from the Sun than Earth." },
  "FARFAROUT": { text: "Nicknamed FarFarOut as a playful one-up on FarOut — discovered by the same team just a month later and even more distant. Its official designation is 2018 AG37." },
};
